
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000f0f"


[font]
size = 12


[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

# [selection]
# save_to_clipboard = true


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window]
opacity = 0.8
startup_mode = "Maximized"
blur = true
decorations = "None"

