theme = "theme"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
soft-wrap.enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


